name: lab05
on: [ push ]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@master
   - name: build library
     run: |
      git submodule update --init --recursive
      cmake -B ./banking_lib_output
      cd banking_lib_output
      make
 tests:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@master
    - name: testing
      run: |
        git submodule update --init --recursive
        cmake -B ./banking_lib_output
        cd banking_lib_output
        make
        ./tests

    - name: install lcov
      run: |
        sudo pip install --user cpp-coveralls
        sudo apt-get install -y lcov

    - name: run gcovr
      run: |
        sudo pip install gcovr
        gcovr tests/test.cpp -o report

    - name: run lcov
      run: lcov --capture --directory . --output-file lcov.info

    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: "./lcov.info"
        github-token: ${{ secrets.github_token }}